### ISSUE TITLE
Provide a way to build Lua from source using SCons

### ISSUE THREAD

**Issue by Xrayez** [Trey2k/lua#11]
**Is your feature request related to a problem? Please describe.**
I've tried to compile the module on Windows using MSVC compiler, but I'm getting link errors.

**Describe the solution you'd like**
I suggest that the module provides `thirdparty/` Lua source so that the module can be seamlessly compiled for all platforms (including export templates). Currently, this repository provides pre-built libraries which are not guaranteed to work in the future.

**Describe alternatives you've considered**
I've tried to resolve this myself with:
```python
#!/usr/bin/env python

Import('env')
env_lua = env.Clone()

env_lua.Append(CPPPATH=["luasrc/include"])

if env['platform'] == "x11":
    env_lua.Append(LIBPATH=['luasrc/libs/linux'])
elif env['platform'] == "windows":
    env_lua.Append(LIBPATH=['luasrc/libs/windows'])
elif env['platform'] == "osx":
    env_lua.Append(LIBPATH=['luasrc/libs/macos'])

if not env.msvc:
    env_lua.Append(LIBS=['liblua'])
else:
    env_lua.Append(LINKFLAGS=['liblua.lib'])

env_lua.add_source_files(env.modules_sources, "*.cpp") #this will add all the cpp files
```

But I still get link errors on Windows. Also notice that I've removed absolute path referencing `#modules/lua`, because it won't work with [`custom_modules`](https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html#custom-modules) built option either.

**Additional context**
I do not personally need Lua support at the moment, but I've added this module to https://github.com/goostengine/godot-modules as a git submodule for people to try out, but had to disable it for now. Thanks for sharing!

**Comment by Trey2k** [comment]
So we has issues before with MSVC, however I was able to get it to build. https://github.com/Trey2k/lua/issues/4

I did try to get lua building from source with SCons but probably due to a lack of familiarity I was not able to get it to work. I will look into a way to get it building from source. Thanks for bringing this up

**Comment by Trey2k** [comment]
So I would love to get lua sources building seamlessly with the rest of the godot source. But I have a severe lack of experience with SCons. Any suggestions on how to go about that properly would be greatly appreciated

**Comment by Xrayez** [comment]
You can take a look at https://github.com/goostengine/goost/blob/gd3/modules/git/SCsub as an example which compiles both module and third-party sources (includes per-platform configuration, a way to define preprocessor values etc.)

**Comment by Xrayez** [comment]
I've completely forgot that there's [`LuaScript` project](https://github.com/perbone/luascript), it also has Lua source bundled, so you may just be able to borrow the code from there... 🙂

**Comment by Trey2k** [comment]
Added in 10ed7172a463c8363c3d26dcb0096307a04e0450

**Comment by Xrayez** [comment]
Alright, reporting that the module compiles for all editor builds now in https://github.com/goostengine/godot-modules, which is currently available via build artifact. 🙂
