### ISSUE TITLE
Use correct naming conventions

### ISSUE THREAD

**Issue by btvoidx** [Trey2k/lua#12]
Lua class in Godot uses camel case for function names, but Godot's [style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#functions-and-variables) suggests snake case.

**Describe the solution you'd like**
Change camelCase to snake_case where needed.
```
killAll -> kill_all
setThreaded -> set_threaded
doFile -> do_file
doString -> do_string
pushVariant -> push_variant
exposeFunction -> expose_function
callFunction -> call_function
luaFunctionExists -> lua_function_exists
```

**Comment by Trey2k** [comment]
Added in 10ed7172a463c8363c3d26dcb0096307a04e0450
