### ISSUE TITLE
Add a way to pull a variant from lua.

### ISSUE THREAD

**Issue by btvoidx** [Trey2k/lua#13]
**Is your feature request related to a problem? Please describe.**
There is no way to get any data from lua except for side-effects from exposed functions, which is really annoying.
For example, if I want to make an enemy for my game, which health is manipulated through lua, then I'll have to expose `set_health(..)` or `set("health", ..)` functions, which is fine, as long as only need to update health. But there could be tens of different variables, at which point it gets annoying.

**Describe the solution you'd like**
Some clear way to pull variant from lua, for example:
```gdscript
var godothealth = 5
lua.pushVariant(5, "luahealth") # godothealth == 5
lua.doFile(...) # Runs and sets local luahealth to 3
godothealth = lua.pullVariant("luahealth") # godothealth == 3
```

**Comment by Trey2k** [comment]
This should be fairly simple to do, I'll look into it today as well as the other issues that have come up while my attention has been else were

**Comment by Trey2k** [comment]
This functionality has been added to the dev branch in 9a6cd7bbd728803ecce88f83ca812298e5613b24. Will be in the next minor release
