### ISSUE TITLE
Nonexistent functions 'callFunction' and 'luaFunctionExists' in base 'Lua'.

### ISSUE THREAD

**Issue by btvoidx** [Trey2k/lua#14]
I tried to follow README to see what this module can do, and it appears that neither `luaFunctionExists` nor `callFunction` exist, at least they aren't exposed to Godot.

Example snippet:
```gdscript
var lua = Lua.new()
lua.doString(self, 'function hello() print("hello") end', "")
lua.callFunction("hello")
```

I am using Windows pre-compiled binary from releases tab.

**Comment by Trey2k** [comment]
Windows pre compiled bin is out of date actually! It should probably be updated

**Comment by Trey2k** [comment]
I have updated the pre built bins in the v1 release https://github.com/Trey2k/lua/releases/tag/v1.0-stable
