### ISSUE TITLE
Can't find Lua module on exported build but it can on editor

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#15]
I can run Lua code on editor side however on builded windows or html game couldn't find lua. I just export via Project>Export...>Windows Desktop

![image](https://user-images.githubusercontent.com/57962685/126962005-2186a64b-38ed-49e0-bd6c-b1c598839d10.png)

I think it is not about my lua code but I will share anyways
```extends Node

onready var lua = Lua.new()

func luaAdd(a, b):
	Debug.put_log(str(a+b)+" luadan çalıştı")
	return a + b

func _ready():
	lua.exposeFunction(self, "luaAdd", "add")
	lua.doString(self,"print(add(2, 4))","luaCallBack")

func luaCallBack(err):
	print(err)```

**Comment by Trey2k** [comment]
Have you properly built the export templates? https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html#creating-windows-export-templates

**Comment by cenullum** [comment]
@Trey2k I had used windows.zip on release page

**Comment by Xrayez** [comment]
Yes, editor and export templates should be treated separately, this is not exclusive to this module. Export templates are just engine binaries without editor tools compiled, by the way.

**Comment by Trey2k** [comment]
> @Trey2k I had used windows.zip on release page.
> 
> oh I think I have to make custom template

Also keep in mind until I can get some time the release page is out of date with the repo

**Comment by cenullum** [comment]
@Trey2k @Xrayez thanks. I saw libraries for linux windows and mac, a library isn't needed for html5 or  there isn't support yet?

**Comment by Trey2k** [comment]
> @Trey2k @Xrayez thanks. I saw libraries for linux windows and mac, a library isn't needed for html5 or there isn't support yet?

I have not tested this as of yet. Ideally I want scons to compile Lua on the fly anyways. So assuming I can get that working we should not have to worry about that

**Comment by Xrayez** [comment]
Godot provides https://github.com/godotengine/godot-build-scripts, I've been using it successfully for my own custom modules.
