### ISSUE TITLE
Invalid parametre type on do_string

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#16]
my code on editor run as expectly, its prints 6 on console but on exported I got this error ![image](https://user-images.githubusercontent.com/57962685/127147503-14dbbcff-5086-44c2-bab5-55d699c3de27.png)

my code

```extends Node

onready var lua = Lua.new()

func luaAdd(a, b):
	return a + b

func _ready():
	lua.exposeFunction(self, "luaAdd", "add")
	lua.doString(self,"print(add(2, 4))","luaCallBack")

func luaCallBack(err):
	print(err)
```

I think liblua in modules\lua\luasrc\libs\windows is old as first init of the repository because it expects  string from me like in README.md examples but in editor I had to add self and callback parametres because of warnings.
![image](https://user-images.githubusercontent.com/57962685/127148926-cceedfe2-a978-44a9-afca-5ea50611234c.png)

![image](https://user-images.githubusercontent.com/57962685/127148281-3e0cd889-2c2d-4731-86c9-5110fbeb2967.png)

First I thought I made  custom export template wrongly however error that say ""lua" isn't declared in the current scope" is gone. and while compiling I saw the lua.cpp
![image](https://user-images.githubusercontent.com/57962685/127147409-dd10b06c-6002-4bb1-ae0b-0512a52a6765.png)

**Comment by Trey2k** [comment]
It looks like the doc is out of date, doString is defined as ```c++
void Lua::doString( String code, bool protected_call , Object* callback_caller , String callback )
```

**Comment by Trey2k** [comment]
Looks like the changes came from https://github.com/Trey2k/lua/pull/8

**Comment by cenullum** [comment]
now as expected on builded game everything is fine but there is still warning on editor. Do I need to compile godot to get rid of the warning?    


 ```extends Node
onready var lua = Lua.new()
func luaAdd(a, b):
	return a + b
func _ready():
	lua.exposeFunction(self, "luaAdd", "add")
	lua.doString("print(add(2, 4))",false , self,"luaCallBack")
func luaCallBack(err):
	print(err)

```

**Comment by cenullum** [comment]
I just made my own custom build with tools=yes and everything is fine now on builded game and editor. whole command here     scons platform=windows target=release_debug tools=yes bits=64 -j 4
