### ISSUE TITLE
Unable to find library -llua while building html5 custom export template

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#17]
I was trying to make custom export template for html5 and I got such an error at the last step.  I think this supposed to be -lua not -llua
![image](https://user-images.githubusercontent.com/57962685/127198480-4ca4178d-503c-4687-a862-3d1a08863fdc.png)

**Comment by Trey2k** [comment]
The issue would be there is no lib for lua on WASM builds currently. -l means link followed by the name of the thing to link. WASM support is one of the things I plan on focusing on. Once I have lua being built form source it should work

**Comment by Trey2k** [comment]
> I was trying to make custom export template for html5 and I got such an error at the last step. I think this supposed to be -lua not -llua
> ![image](https://user-images.githubusercontent.com/57962685/127198480-4ca4178d-503c-4687-a862-3d1a08863fdc.png)

Can you try the same thing with the dev branch? https://github.com/Trey2k/lua/tree/dev

**Comment by cenullum** [comment]
same thing 
![image](https://user-images.githubusercontent.com/57962685/127213491-d0aa4163-d56e-4448-8712-b54f567e1ce0.png)

**Comment by Trey2k** [comment]
Hmm, well I am not too sure. Because the dev branch is building lua from source. Ill do some testing

**Comment by cenullum** [comment]
I cloned godot again and ...tree/dev. it builded custom export template without -llua error then I got my html game build but I got this error on my game
![image](https://user-images.githubusercontent.com/57962685/127220619-3841ae02-5c7f-40a5-941b-8f848f26111c.png)
 then I saw falles comment https://github.com/godotengine/godot/issues/45425#issuecomment-767007486

so deleted part of util.js
![image](https://user-images.githubusercontent.com/57962685/127220590-05199e79-c351-4cdb-a42c-3de55054bc7d.png)

then open mode wm+ error is gone but became full balck screen and got this error  now I will clone godot again becuase there was a warning that i underestimated i will take a screenshot of it 
![image](https://user-images.githubusercontent.com/57962685/127221968-afa05dff-2f04-4311-8087-eef5b46b40dc.png)

**Comment by cenullum** [comment]
there is a problem about audio. I got this warning over 10 times while building
![Ekran görüntüsü 2021-07-27 233936](https://user-images.githubusercontent.com/57962685/127227005-f3210732-6769-4c97-9728-316e6e91f85a.png)

**Comment by cenullum** [comment]
I tried to build on current godot instead of 3.2.3 and got same audio_server.h error. so the last error is related to my computer so probably lua works on html5. can you release a web custom export template? or it seems I can't test my game until figure it out   @Trey2k

**Comment by Trey2k** [comment]
> I tried to build on current godot instead of 3.2.3 and got same audio_server.h error. so the last error is related to my computer so probably lua works on html5. can you release a web custom export template? or it seems I can't test my game until figure it out @Trey2k

I will see what I can do

**Comment by Trey2k** [comment]
I get the exact same errors on my export templates. Not exactly sure what the issue is

**Comment by Trey2k** [comment]
Okay @cenullum I got it working! 
![image](https://user-images.githubusercontent.com/7241029/127420533-ad6def64-4975-4d1d-95b1-52637ca4411c.png)
Export templates and updated release builds will be up tonight!
