### ISSUE TITLE
 call_function can't return value

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#19]
**Is your feature request related to a problem? Please describe.**
I think call_function can't return values yet.

**Describe the solution you'd like**
```
if(lua.lua_function_exists("LuaFunctionName") ):
     var value = lua.call_function( "LuaFunctionName",[])
print(value)

```
```
function LuaFunctionName()
     return "Hello from lua"
end
```

**Comment by Trey2k** [comment]
This is correct, currently call_function will not return a value. Should be a easy fix.

**Comment by Trey2k** [comment]
Okay I think this is probably the best way to support it. It will always return a Variant now. If lua returns nothing the Variants value will be null. Checkout the dev branch https://github.com/Trey2k/lua/tree/dev

**Comment by Trey2k** [comment]
Added in 1ff4f705ce9a8eace1afb232668b9532d01961f6. Expect it in the next minor release

**Comment by cenullum** [comment]
Something is wrong I created a project for you to see too 
"stats" value stay as 123 which is initial value
[Test.zip](https://github.com/Trey2k/lua/files/6903615/Test.zip)

**Comment by Trey2k** [comment]
> Something is wrong I created a project for you to see too
> "stats" value stay as 123 which is initial value
> [Test.zip](https://github.com/Trey2k/lua/files/6903615/Test.zip)
> you can drag and drop the lua file and press f9 to increase test value, in lua it adds test to stats value

Silly bug haha, I forgot to pop the return value off the stack. So in a since it cached the initial value
