### ISSUE TITLE
push_varient doesn't update the value

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#20]
**Is your feature request related to a problem? Please describe.**
push_varient can send value but when I change value on godot side, it is still old value  on lua side

**Describe the solution you'd like**
```
var test = 3
func _ready():
	lua.push_variant(test,"valueFromGodot")
         lua.do_file(PATH_OF_LUA_FILE,true , self,"lua_call_back")

func _input(event):
	if event is InputEventKey:
		if event.is_pressed() and event.scancode==KEY_F9:
			test+=1
                       print("test value on godot ",test)
			if(lua.lua_function_exists("Run") ):
				lua.call_function( "Run",[])
```

```
function Run()
    print("valueFromGodot "..valueFromGodot)
    
end
```
maybe there can be a boolean  to decide whether or not this will be updated
lua.push_variant(test,"valueFromGodot",true)

**Comment by Trey2k** [comment]
So the way it works is it only pushes a copy of the variant to lua. There may be a way to push a pointer to lua. But you may find it easier to just push it again when it is updated.

**Comment by Trey2k** [comment]
Here is a example of what I mean

```gdscript
extends Node2D

onready var lua = Lua.new()
# Declare member variables here. Examples:
# var a = 2
# var b = "text"


var test = 3
func _ready():
	lua.push_variant(test,"valueFromGodot")
	lua.do_string("function Run() print(valueFromGodot) end")

func _input(event):
	test+=1
	lua.push_variant(test,"valueFromGodot")
	print("test value on godot ",test)
	if(lua.lua_function_exists("Run") ):
		lua.call_function( "Run",[])
```
It is important to keep in mind this is not very performant. I would try to avoid globals as much as you can and pass what data is needed as arguments. If this where to be implemented it would probably function exactly the same except c++ would have to constantly check if the value changed added even more overhead.
