### ISSUE TITLE
Can't change value while doing "while loop"

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#22]
[Test.zip](https://github.com/Trey2k/lua/files/6907881/Test.zip)

In the project I was expecting value will be 0 after pressing F9 which runs trigger function in lua. I also got this error 

test2.lua file:
 ```

value=1

function trigger()
    Log("Old value "..value)
    value=0
    Log(value)
end

while true do 
    value=value+1
end
```
![image](https://user-images.githubusercontent.com/57962685/127661328-c333185c-26ab-4f96-ad58-ac314a442b54.png)

**Comment by Trey2k** [comment]
If the lua instance is currently executing I dont think it will let you call another function within the same instance

**Comment by cenullum** [comment]
do I need to seperate while loop and functions? If so how can I reach to another lua's values in a lua directly? with dofile(file.lua) ? or I can use godot as mediator

**Comment by Trey2k** [comment]
I think the best option would be to have a GDScript exposed to lua for the purpose of sending the updated data in the while loop if you need to have a infinite loop in lua.

**Comment by cenullum** [comment]
but what would happen to lua functions? I wouldn't be able to use them

**Comment by cenullum** [comment]
haha I found a way. I just simply call_function at the end of process , I wasn't expect it :)
the project
[Test.zip](https://github.com/Trey2k/lua/files/6908700/Test.zip)

f9 to reset both of godot value and lua value

**Comment by Trey2k** [comment]
> haha I found a way. I just simply call_function at the end of process , I wasn't expect it :)
> the project
> [Test.zip](https://github.com/Trey2k/lua/files/6908700/Test.zip)
> 
> you need to drag and drop test3.lua
> f9 to reset both of godot value and lua value
> 
> the issue isnt solved but workaround seems easy enough for me so I don't need infinite loop now. you decide whether to close it or not.
> 
> And also now you don't need a library for timer because I can send delta value of process via call_function

Honestly I think that is the proper solution anyways. As far as I know thats how most lua apis handle it. You create a game loop function in lua that is called. Only one process can run in a single lua instance without adding some multi threading options to lua.
