### ISSUE TITLE
it crashes if i don't get reference of lua

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#24]
I realized this while adding lua to array it doesnt crash however if I don't reference of local lua game crashes. I was expecting just lua being destroyed warning and the game to continue
![image](https://user-images.githubusercontent.com/57962685/129443928-1eefa8c4-3878-44ef-8464-5a355bda330a.png)

```
func _files_dropped(files, screen):
	
	if files[0].get_extension() =="lua":
		output(files)
		var lua = Lua.new()
		lua.set_threaded(true)
		lua.expose_function(self, "output", "log")
		lua.do_file(files[0],true , self,"output")
                #lua_cores.append(lua)#if this line is comment, game crashes


func output(_log):
	get_node("CanvasLayer/Control/output").text+="\n"+str(_log)
	print(_log)
```

the lua file that I test
```
function test(message)
    log(message)
end

test("test1")
test("test8")
test("test7")
test("test1")
test("test9")
test("test0")
test("test5")
test("test1")
test("test3")
test("test2")
```

**Comment by Trey2k** [comment]
So the reason why is because you have threading enabled meaning the next line of code in godot will execute immediately. If you do not add the object to some sort of array or similar the object will be destroyed while code is running.

**Comment by cenullum** [comment]
sorry I forgot the set_threaded(true) part, now I understand why it's not working and you are right it prints all the lines when thread is false.
