### ISSUE TITLE
cant send some letter from lua to godot

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#25]
![image](https://user-images.githubusercontent.com/57962685/129460133-b1238860-5c3d-4184-b41a-0d959cb1ac4d.png)

letters here:    ııığşüçö
and somehow  lowercase letter  of  " I " turns to number one

log function is just exposed func to print to console and in game label

**Comment by Trey2k** [comment]
So this would be because LUA is written in C which uses ASCII and 'ııığşüçö' is not valid ASCII text so it dose not know what to do with it. Ill try to think of a way around this but not sure if I will find one.

**Comment by cenullum** [comment]
What version do you use? I think  in lua 5.3 they added utf8 however I'm not sure does it require anything else. I guess there must be long boring functions and modder will have to specify which language do they use or maybe you can find a way to hide the functions by making them builtin somehow I dont know.

**Comment by Trey2k** [comment]
Looks like there is a utf8 lib in the standard library for lua. I'll mess around with it

**Comment by Trey2k** [comment]
This will be resolved with the addition of bind_libs in v2. added in e205c0bd7917ea1f557e59b5eaedddc85e5d3f5c
