### ISSUE TITLE
Checking parameter name 

### ISSUE THREAD

**Issue by cenullum** [Trey2k/lua#26]
```
extends Node2D

onready var lua = Lua.new()

func _ready():
	lua.do_file("user://luaFile.lua")
	if( lua.lua_parametre_exists("set_player_position","new_position" )):
             print("There is new_position parametre")
```
or it can be more useful with this

```
extends Node2D

onready var lua = Lua.new()

func _ready():
	lua.do_file("user://luaFile.lua")

        if( lua.lua_function_exists("set_player_position") ):
	       var parameters=   lua.get_all_parameters_name("set_player_position" )#returns string array that contains name of parameters
               print(parameters)
```
I saw functions can be called with less parameters in lua
![image](https://user-images.githubusercontent.com/57962685/134554201-990c5c3c-d86f-4a48-b09b-6f7a901235c9.png)
then I got a idea that is using parameters as tag

In terms of my game, When there is a "network_id" parameter in a function I consider this is a network function so it will be allowed to run remotely.

If the feature request isn't possible then I think I had to cache functions names in string array to check out is it special function however it is so unproductive

**Comment by Trey2k** [comment]
This may be possible to implement in C. I will need to find a way. I know you could implement this in pure Lua using the debug lib. Although for it to be possible it would have to be included here https://github.com/Trey2k/lua/blob/34dac9a8fd97f2b1a8f06a95dbf6c4009bbc78f2/lua.cpp#L39 I am unsure if the debug lip has any potentially dangerous functions like the OS lib dose. I will do further research on it.

**Comment by cenullum** [comment]
now I'm thinking about it, returning the name of the functions in lua as array can also be useful.

**Comment by Trey2k** [comment]
Sadly this dose not seem to be possible [source](https://stackoverflow.com/questions/52552237/lua-c-api-how-to-get-a-function-name). I think a could way to archive this however would be by pushing global variants before you call the func.
