### ISSUE TITLE
Can i add library for lua?

### ISSUE THREAD

**Issue by elonam** [Trey2k/lua#28]
Can i add library to lua?

**Comment by Trey2k** [comment]
The simplest way to add another library to lua is to add it to the list [here]( https://github.com/Trey2k/lua/blob/89fff9319f157c144b8d7b2fcd01434b13e80387/lua.cpp#L3#) and recompile it.
Currently there is not a way to add another list via GDScript however this is something that could be looked into

**Comment by Trey2k** [comment]
Added in e205c0bd7917ea1f557e59b5eaedddc85e5d3f5c with the method bind_libs for v2
