### ISSUE TITLE
Error building on Windows 10

### ISSUE THREAD

**Issue by rilpires** [Trey2k/lua#3]
I've cloned this repo under modules/ folder of a 3.2.3-stable Godot Repo and then started scons simply with "scons". Apparently everything compiled, this error goes at the last step (linking final executable)

`scons: Reading SConscript files ...`
`Automatically detected platform: windows`
`Configuring for Windows: target=debug, bits=default`
`Found MSVC compiler: amd64`
`Compiled program architecture will be a 64 bit executable (forcing bits=64).`
`YASM is necessary for WebM SIMD optimizations.`
`WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!`
`Checking for C header file mntent.h... (cached) no`
`scons: done reading SConscript files.`
`scons: Building targets ...`
`[Initial build] Linking Program        ==> bin\godot.windows.tools.64.exe`
`LINK : fatal error LNK1181: não foi possível abrir o arquivo de entrada 'liblua.windows.tools.64.lib'`( Translating: Couldn't open input file 'liblua.windows.tools.64.lib')
`scons: *** [bin\godot.windows.tools.64.exe] Error 1181`
`scons: building terminated because of errors.`

I'm not familiar with windows linkage, but I guess scons should had accepted `luasrc/libs/windows/liblua.a` but it didn't?

**Comment by Trey2k** [comment]
Where you using MingW64 or visual studio?

**Comment by rilpires** [comment]
>Where you using MingW64 or visual studio?
 Visual Studio (MSVC)

> try downloading the lua libs from [here](https://sourceforge.net/projects/luabinaries/files/5.3/Windows%20Libraries/Static/lua-5.3_Win64_vc9_lib.zip/download) rename the file to liblua.lib and place it in the windows folder. Let me know if this works and I will add it to the main repo

Tried, no success. Even tried to rename it to "lualib.windows.opt.tools.64.lib". Same error.

**Comment by Trey2k** [comment]
Ill boot up my windows VM and see if I can get a successful build with MSVC. Ill keep you posted

**Comment by Trey2k** [comment]
I got a successful build, let me know if you have any other issues.

**Comment by Trey2k** [comment]
Fixed in 2f176e0d63438275fc82b7bf0879139a6edc1020

**Comment by rilpires** [comment]
Also, what was needed to fix it in first place? Did you build out the .lib file yourself?

**Comment by Trey2k** [comment]
I think I linked you to the wrong lua version, I downloaded 5.3.4 and it worked. I linked you to 5.3. Besides that I didn't do anything differently. And I will create a new issue for the tools build. Its weird that MSVC needs specific naming after the name of the lib its self. I'm not too familiar with MSVC so hopefully I can find a better method.
