### ISSUE TITLE
The repo contains binary bc files and the gitignore doesn't include standard exclusions.

### ISSUE THREAD

**Issue by poikilos** [Trey2k/lua#30]
Are the bc files llvm intermediate files?

The .gitignore file is rather thin. Consider adding:
- [Python.gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore)
- [C++.gitignore](https://github.com/github/gitignore/blob/main/C++.gitignore)
- `*.bc`

You would have to delete the files as a separate commit before changing the .gitignore file in a related way.

**Comment by Trey2k** [comment]
Yes i actually saw this recently while working on the 1.1 release. It will be fixed son sorry about that.

**Comment by Trey2k** [comment]
Fixed in fedb394fbda235b240f7740c57c5af2e5e503ab3
