### ISSUE TITLE
(Not a bug or something, just a question)

### ISSUE THREAD

**Issue by sannelo** [Trey2k/lua#38]
I apologize for writing this in Issue.

How can I add Sockets support?
Thanks for the answer!

**Comment by sannelo** [comment]
If you can, add a "Discussions" section. Thanks!

**Comment by Trey2k** [comment]
There are several ways this could be done. The simplest way however would be to either expose directly or make your own API around (StreamPeerTCP)[https://docs.godotengine.org/en/stable/classes/class_streampeertcp.html] to expose to Lua.

Also Discussions section has been added.
