### ISSUE TITLE
Issue with MSVC tools build

### ISSUE THREAD

**Issue by Trey2k** [Trey2k/lua#4]
Thank you, it builds properly now, although, since I was using `target=release_debug` and `tools=yes`, I needed to rename the included `liblua.windows.tools.64.lib` to `liblua.windows.opt.tools.64.lib` . Seems something simple to resolve with scons but I'm very limited in this knowledge

_Originally posted by @rilpires in https://github.com/Trey2k/lua/issues/3#issuecomment-814351521_

**Comment by Trey2k** [comment]
Interesting information found here. https://github.com/godotengine/godot/issues/20045
Will test removing suffix shortly

**Comment by Trey2k** [comment]
Fixed in 4103aa3a59014c963071b4614659b8ab9efd6d8a
@rilpires can you confirm it works as expected now in your env?

**Comment by rilpires** [comment]
It builds! (tried with `target=release_debug` and `tools=yes`)
Thank you
