### ISSUE TITLE
Problem with await functions.

### ISSUE THREAD

**Issue by sannelo** [Trey2k/lua#40]
When I call GDScript from under Lua, it (Lua) does not wait for the return of parameters from the function (GDScript), but continues to go further through the code.

Lua:
![Снимок экрана 2022-07-12 в 20 46 31](https://user-images.githubusercontent.com/36744321/178559436-41700cbd-b9b4-434d-a903-5774f80ffb89.png)

get_pos() return string (x + " " + y) without using "await". 
up() - move_up()

GDScript: 
![Снимок экрана 2022-07-12 в 20 47 27](https://user-images.githubusercontent.com/36744321/178559731-aeb9a451-cdc8-46c5-8e8f-ed77c3d73d62.png)

Output: 
![Снимок экрана 2022-07-12 в 20 46 53](https://user-images.githubusercontent.com/36744321/178559886-2c966bea-56d0-42e8-b3e7-edc0f961413d.png)

**Comment by BestestHD** [comment]
I'm not sure how applicable this for you, but this is how I'm handling events:
I have the bindings themselves in GDScript, example being
_message (lua) corresponding to message (gdscript)
then i have a file for each binding which yields, so it has a function reading something like
`function message(msg)
    _message(msg)
    yield()
end`

this gets inserted at the top of each script upon loading. if i don't want to wait, i just call _message

As far as I can tell, you need to call yield from the lua script, just awaiting in the GDScript function is useless. Then emit a signal from the GDScript function once it's finished awaiting and attach that to a function which resumes the Lua script (or does nothing if there's no paused script)
it might also be good to assign a key to each function which you emit with that signal so you don't accidently resume the Lua script from the wrong function.

**Comment by sannelo** [comment]
In Lua, up() returns true in all cases, which is impossible from the point of view of the code.

**Comment by Trey2k** [comment]
I think the main issue is awaiting in GDScript, lua dosnt play nicely with the native GDScript scheduling. You would probably want to yield from lua. As far as it always returning true my best guess is the context of the is_move variable is not captured by the function when its passed to lua. Several ways you could fix this. I think the easiest would be to create a "player" object that has a .up function that way you can be sure you have everything in scope.
