### ISSUE TITLE
Any way to pass an array to lua and back?

### ISSUE THREAD

**Issue by kicknbrit** [Trey2k/lua#45]
I want to send a PackedByteArray to lua and have it work with it. Is there any way to do this?
Also will luajit ever be supported, or is there a way to add it myself? (sorry if this has been asked already)
Thanks a lot for this module! :D

**Comment by Trey2k** [comment]
To answer your first question, you should be able to just pass a PackedByteArray with push_variant. If you want lua to have access to its constructor you can use expose_constructor.

As far as luajit goes I am definitely open to ot but have no experience with it myself. I'm not sure what the feasibility is currently.

**Comment by kicknbrit** [comment]
Sorry I got a little confused. I missed a part of the wiki. 
It works perfectly, thank you so much. I really needed this for my game!

I haven't taken much time to understand Gdextension so I am not sure how that would work either.
But this is fine for me, thank you!

**Comment by kicknbrit** [comment]
Is there a size limit for arrays? 
I'm having a hard time allocating large PackedByteArrays with around 500,000+ indices. (I'm working with voxel data)

**Comment by Trey2k** [comment]
> Is there a size limit for arrays? 
> I'm having a hard time allocating large PackedByteArrays with around 500,000+ indices. (I'm working with voxel data)

There should not be a issue with it. May open a new issue with more info if you keep having issues.

**Comment by kicknbrit** [comment]
Okay
