### ISSUE TITLE
Exposed functions with no return, returning nil to lua

### ISSUE THREAD

**Issue by Trey2k** [Trey2k/lua#6]
> * Is there a problem to exposedFunctions always return a value? If in GDscript they don't return anything, in Lua it will appear as a nil value. To pass nil values can be useful (before wasn't able to push GD Null values)

There first way to achieve this that comes to mind is to pass along a boolean with the exposeFunction method stating weather it has a return type or not. There is also the question of how useful this will be. While in lua returning nil and nothing are different they don't differ much. For [referance](https://stackoverflow.com/questions/18522299/returning-nil-from-a-lua-function-in-c-vs-returning-0-values). @rilpires I would like to hear your opinion on the matter

**Comment by rilpires** [comment]
I don't see any problem with always returning at least nil. Also, isn't it how GDScript handles non-returning functions? I don't think anyone would care 🤷
