### ISSUE TITLE
Error executing threaded code right after creating Lua object

### ISSUE THREAD

**Issue by rilpires** [Trey2k/lua#9]
The following script doesn't works. It freezes the program and closes shortly after. No message is shown in console.

```gdscript
func _ready():
	var lua = Lua.new()
	lua.doString("for i=1,10,1 do print('Hello lua!') end")
```

Strangely, this works
```gdscript
onready var lua = Lua.new()
func _ready():
	lua.doString("for i=1,10,1 do print('Hello lua!') end")
```

This works
```gdscript
func _ready():
	var lua = Lua.new()
        lua.setThreaded(false)
	lua.doString("for i=1,10,1 do print('Hello lua!') end")
```

Waiting a single frame doesn't freeze the program, but throwns an error message
```gdscript
func _ready():
	var lua = Lua.new()
	yield( get_tree() , "physics_frame" )
	lua.doString("for i=1,10,1 do print('Hello lua!') end")
```
error: `[string "for i=1,10,1 do print('Hello lua!') end"]:1: syntax error near 'i'`

I think maybe running a separated thread can be tricky. We could use the godot builtin thread model to run Lua and deprecate this module's own thread model... still gotta check if it works properly

**Comment by Trey2k** [comment]
Weird... I will do some testing my self. I do know godot suggest to use c++ and c# own threading classes rather than theirs. But if it works better I am not opposed.

**Comment by rilpires** [comment]
> I do know godot suggest to use c++ and c# own threading classes rather than theirs

really? where can I read about it?

**Comment by Trey2k** [comment]
So I did some testing, the bug occurs on windows and Linux. It seems to only happen if the lua object is a local variable. as this works perfectly fine. I don't have any ideas of the cause yet.
```gdscript
extends Node2D

var lua

func _ready():
	lua = Lua.new()
	lua.doString("for i=1,10,1 do print('Hello lua!') end")
```

**Comment by Trey2k** [comment]
Scratch that, I just found the cause. Since its a local variable once _ready() is done running the context of the lua object gets destroyed. And unless you yield 2 frames AFTER you call doString() the thread does not have time to execute the code.

This works

```gdscript
extends Node2D

func _ready():
	var lua = Lua.new()
	lua.doString("for i=1,10,1 do print('Hello lua!') end")
	yield( get_tree() , "physics_frame" )
	yield( get_tree() , "physics_frame" )
```

**Comment by Trey2k** [comment]
This makes a lot more sense now. Infract its technically not even a bug. Its just not thread safe to do it like this. 50% of the time yielding one frame will still execute the code as well. The question now, is there even a way to prevent the destruction of the object. Or do we just leave this to the users to prevent. We could implement a call back for completion of execution but this would kind of take away the point of multi threading anyways.

**Comment by mcsamuel** [comment]
Look to me like this is not a bug. I think you are correct that this should just be documented.

**Comment by rilpires** [comment]
>```gdscript
>func _ready():
>	var lua = Lua.new()
>	lua.doString("for i=1,10,1 do print('Hello lua!') end")
>```
Of course it won't work... I totally forgot about the local scope...
Yeah, there isn't any problem apparently, just a proper documentation may be enough. Maybe we can print a warn when `Lua` object is being freed and is executing lua code?

**Comment by Trey2k** [comment]
> > ```gdscript
> > func _ready():
> >   var lua = Lua.new()
> >   lua.doString("for i=1,10,1 do print('Hello lua!') end")
> > ```
> 
> Of course it won't work... I totally forgot about the local scope...
> Yeah, there isn't any problem apparently, just a proper documentation may be enough. Maybe we can print a warn when `Lua` object is being freed and is executing lua code?

I totally forgot about local scope too when I was initially looking into it haha. It wasn't until I finished writing that it only happens with local variables that it clicked. 



> Look to me like this is not a bug. I think you are correct that this should just be documented.

This is what I am going to do. For now I am going to set threaded to false by default and implement @rilpires idea about printing a warning message when its free. And of course document it. I will be commiting some changes soon.
